import type { Metadata } from "next";
import "./globals.css";
import { Roboto_Mono, Rubik} from 'next/font/google';

// Define fonts used for page
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  weight: ["100", "700"],
})

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  weight: ["300", "900"],
})

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoMono.variable} ${rubik.variable} bg-neutral-100`}>
        
        {children}
        
      </body>
    </html>
  );
}
